/**
 * Onboard Command - Interactive Setup Wizard
 * Guides users through CogniMesh v5.0 configuration
 */

import { existsSync, mkdirSync } from 'fs';
import { join } from 'path';
import { randomBytes } from 'crypto';
import { createInterface } from 'readline';
import * as steps from './onboard-steps/index.js';
import * as f from './utils/formatters.js';

const rl = createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

/**
 * Generate .env file content from configuration
 */
function generateEnvFile(config) {
  const jwtSecret = randomBytes(48).toString('base64');
  const sessionSecret = randomBytes(48).toString('base64');
  const securityPepper = randomBytes(32).toString('base64');

  return `# CogniMesh v5.0 - Environment Configuration
# Generated by onboard wizard on ${new Date().toISOString()}

# ============================================================
# Essential Configuration (Required)
# ============================================================

# Node environment: development | test | production
NODE_ENV=development

# Main server port
COGNIMESH_PORT=${config.ports?.main || 3000}

# Dashboard port
DASHBOARD_PORT=${config.ports?.dashboard || 3001}

# WebSocket server port
WS_PORT=${config.ports?.ws || 8080}

# ============================================================
# AI Client Configuration
# ============================================================

# Feature flags (enable clients you have installed)
FEATURE_CLAUDE=${config.clients?.claude?.enabled || false}
FEATURE_CODEX=${config.clients?.codex?.enabled || false}
FEATURE_KIMI=${config.clients?.kimi?.enabled || false}

# Client CLI paths (auto-detected or manually configured)
${config.clients?.claude?.path ? `CLAUDE_CLI_PATH=${config.clients.claude.path}` : '# CLAUDE_CLI_PATH='}
${config.clients?.codex?.path ? `CODEX_CLI_PATH=${config.clients.codex.path}` : '# CODEX_CLI_PATH='}
${config.clients?.kimi?.path ? `KIMI_CLI_PATH=${config.clients.kimi.path}` : '# KIMI_CLI_PATH='}

# ============================================================
# GitHub Integration
# ============================================================

${config.github?.token ? `GITHUB_TOKEN=${config.github.token}` : '# GITHUB_TOKEN='}
GITHUB_REPO=

# ============================================================
# Security (Auto-generated - Change in production!)
# ============================================================

# JWT secret for authentication (min 32 characters)
JWT_SECRET=${jwtSecret}

# Session secret (min 32 characters)
SESSION_SECRET=${sessionSecret}

# Security pepper for hashing
SECURITY_PEPPER=${securityPepper}

# Admin credentials
ADMIN_USERNAME=${config.admin?.username || 'admin'}
ADMIN_PASSWORD=${config.admin?.password || 'admin'}

# ============================================================
# Database & Storage
# ============================================================

DATABASE_PATH=${config.dirs?.data || './data/db'}/cognimesh.db
STATE_PATH=${config.dirs?.state || './data/state'}
DATA_DIR=${config.dirs?.base || './data'}

# ============================================================
# Deployment Configuration
# ============================================================

DEPLOYMENT_MODE=${config.deployment?.mode || 'local'}
DEPLOYMENT_PORTS=${JSON.stringify(config.deployment?.ports || {})}

# ============================================================
# System Settings
# ============================================================

BIOS_MODE=OPERATIONAL
AUTO_UPDATE=true
LOG_LEVEL=INFO
DASHBOARD_ENABLED=true

# ============================================================
# Optional: Advanced Configuration
# ============================================================
# See .env.example for all available options
# ============================================================
`;
}

/**
 * Show progress indicator
 */
function showProgress(current, total, label) {
  console.log();
  console.log(f.progressBar(current, total, { 
    width: 40, 
    showPercent: true,
    showCount: true 
  }));
  console.log(f.colorize(`Step ${current}/${total}: ${label}`, 'cyan'));
  console.log();
}

/**
 * Main onboard command
 */
export async function onboard(options = {}) {
  const { 
    yes = false, 
    run = false
  } = options;

  const config = {
    dirs: null,
    github: null,
    clients: null,
    deployment: null,
    admin: null,
    ports: null
  };

  const results = [];
  const TOTAL_STEPS = 10;

  // Step 1: Welcome
  showProgress(1, TOTAL_STEPS, 'Welcome');
  await steps.showWelcome();
  
  if (!yes) {
    await question(f.colorize('  Press Enter to continue (or Ctrl+C to cancel)...', 'dim'));
    console.log();
  }

  // Step 2: Prerequisites
  showProgress(2, TOTAL_STEPS, 'Checking Prerequisites');
  const prereqResult = await steps.checkPrerequisites({ skipOnFailure: yes });
  results.push(prereqResult);
  
  if (!prereqResult.success && !yes) {
    console.log(f.error('Prerequisites check failed. Use --yes to skip this check.'));
    return { success: false, message: 'Prerequisites not met' };
  }

  // Step 3: Data Directory
  showProgress(3, TOTAL_STEPS, 'Configuring Data Directory');
  const dataDirResult = await steps.configureDataDir({ yes });
  results.push(dataDirResult);
  config.dirs = dataDirResult.data?.dirs;

  // Step 4: GitHub Configuration
  showProgress(4, TOTAL_STEPS, 'GitHub Integration');
  const githubResult = await steps.configureGitHub({ yes });
  results.push(githubResult);
  config.github = {
    token: githubResult.data?.token ? options.githubToken : null,
    validated: githubResult.data?.validated
  };

  // Step 5: AI Clients
  showProgress(5, TOTAL_STEPS, 'AI Client Configuration');
  const clientsResult = await steps.configureAIClients({ yes });
  results.push(clientsResult);
  config.clients = clientsResult.data?.clients;

  // Step 6: Deployment Mode
  showProgress(6, TOTAL_STEPS, 'Deployment Configuration');
  const deployResult = await steps.configureDeployment({ yes });
  results.push(deployResult);
  config.deployment = {
    mode: deployResult.data?.mode,
    ports: deployResult.data?.ports
  };
  config.ports = deployResult.data?.ports;

  // Step 7: Create Admin
  showProgress(7, TOTAL_STEPS, 'Creating Admin User');
  const adminResult = await steps.createAdmin({ yes });
  results.push(adminResult);
  config.admin = {
    username: adminResult.data?.username,
    password: adminResult.data?.password,
    generated: adminResult.data?.generated
  };

  // Step 8: Database Setup
  showProgress(8, TOTAL_STEPS, 'Database Setup');
  const dbResult = await steps.setupDatabase({ 
    yes, 
    dataDir: config.dirs?.base,
    migrate: true 
  });
  results.push(dbResult);

  // Step 9: Test Connections
  showProgress(9, TOTAL_STEPS, 'Testing Connections');
  const testResult = await steps.testConnections({ 
    clients: config.clients,
    githubToken: options.githubToken,
    skipOnFailure: yes 
  });
  results.push(testResult);

  // Generate .env file
  console.log(f.colorize('Generating configuration files...', 'cyan'));
  console.log();

  const envContent = generateEnvFile(config);
  const envPath = join(process.cwd(), '.env');

  // Backup existing .env if present
  if (existsSync(envPath) && !yes) {
    const backup = await question(f.colorize('  .env exists. Create backup? [Y/n]: ', 'dim'));
    if (backup.toLowerCase() !== 'n') {
      const backupPath = `${envPath}.backup-${Date.now()}`;
      writeFileSync(backupPath, envContent);
      console.log(f.success(`  Backup created: ${backupPath}`));
    }
  }

  writeFileSync(envPath, envContent);
  console.log(f.success(`Created .env file at ${envPath}`));
  console.log();

  // Step 10: Start Services (optional)
  showProgress(10, TOTAL_STEPS, 'Starting Services');
  const startResult = await steps.startServices({ run, yes });
  results.push(startResult);

  // Final Summary
  console.log(f.header('SETUP COMPLETE', 'box'));
  console.log();

  // Configuration summary
  console.log(f.colorize('Configuration Summary:', 'bright'));
  console.log(f.divider());
  console.log(f.keyValue({
    'Data Directory': config.dirs?.base,
    'Deployment Mode': config.deployment?.mode,
    'Main Port': config.ports?.main,
    'Dashboard Port': config.ports?.dashboard,
    'AI Clients': Object.entries(config.clients || {})
      .filter(([, c]) => c.enabled)
      .map(([id]) => id)
      .join(', ') || 'None',
    'GitHub': config.github?.validated ? 'Connected' : 'Not configured',
    'Admin User': config.admin?.username
  }, { indent: 2 }));
  console.log(f.divider());
  console.log();

  // Next steps
  console.log(f.colorize('Next Steps:', 'bright'));
  console.log();
  
  if (!run) {
    console.log(f.colorize('  1. Start the services:', 'cyan'));
    console.log(f.colorize('     cognimesh onboard --run', 'dim'));
    console.log(f.colorize('     or', 'dim'));
    console.log(f.colorize('     npm start', 'dim'));
    console.log();
  }
  
  console.log(f.colorize('  2. Access the dashboard:', 'cyan'));
  console.log(f.colorize(`     http://localhost:${config.ports?.dashboard || 3001}`, 'dim'));
  console.log();
  
  console.log(f.colorize('  3. Check system status:', 'cyan'));
  console.log(f.colorize('     cognimesh status', 'dim'));
  console.log();
  
  console.log(f.colorize('  4. View available commands:', 'cyan'));
  console.log(f.colorize('     cognimesh --help', 'dim'));
  console.log();

  // Save admin credentials notice
  if (config.admin?.generated) {
    console.log(f.warning('⚠️  IMPORTANT: Save your admin credentials securely!'));
    console.log(f.colorize(`   Username: ${config.admin.username}`, 'cyan'));
    console.log(f.colorize(`   Password: ${config.admin.password}`, 'cyan'));
    console.log();
  }

  console.log(f.success('Onboarding complete! 🎉'));
  console.log();

  // Close readline
  rl.close();

  return {
    success: true,
    data: {
      config: {
        dirs: config.dirs?.base,
        deployment: config.deployment?.mode,
        ports: config.ports,
        clients: Object.keys(config.clients || {}).filter(id => config.clients[id].enabled),
        admin: config.admin?.username
      },
      results: results.map(r => ({
        step: r.data?.step,
        success: r.success,
        message: r.message
      }))
    },
    message: 'Onboarding completed successfully'
  };
}

export default onboard;
