/**
 * Environment Variables Check
 * Validates required environment variables are set
 */

import * as f from '../utils/formatters.js';  // eslint-disable-line no-unused-vars

const REQUIRED_ENV_VARS = [
  { key: 'GITHUB_TOKEN', required: true, minLength: 10 },
  { key: 'DATABASE_PATH', required: false, defaultValue: './data/cognimesh.db' },
  { key: 'STATE_PATH', required: false, defaultValue: './data/state' },
  { key: 'COGNIMESH_PORT', required: false, defaultValue: '3000' },
  { key: 'JWT_SECRET', required: true, minLength: 32 }
];

/**
 * Check environment variables
 * @param {Object} options - Check options
 * @returns {Promise<Object>} Check result
 */
export async function checkEnvironment(_options = {}) {
  const missing = [];
  const invalid = [];
  const present = [];

  for (const envVar of REQUIRED_ENV_VARS) {
    const value = process.env[envVar.key];

    if (!value) {
      if (envVar.required) {
        missing.push(envVar.key);
      } else {
        present.push({ key: envVar.key, value: envVar.defaultValue, isDefault: true });
      }
      continue;
    }

    if (envVar.minLength && value.length < envVar.minLength) {
      invalid.push({
        key: envVar.key,
        message: `Too short (minimum ${envVar.minLength} characters)`
      });
      continue;
    }

    // Mask sensitive values
    const displayValue = envVar.key.includes('TOKEN') || envVar.key.includes('SECRET')
      ? '*'.repeat(Math.min(value.length, 8))
      : value;

    present.push({ key: envVar.key, value: displayValue });
  }

  // Check for production security settings
  const warnings = [];
  if (process.env.NODE_ENV === 'production') {
    if (process.env.JWT_SECRET === 'your_jwt_secret_here_change_in_production_minimum_32_chars') {
      warnings.push('Default JWT_SECRET detected in production');
    }
    if (process.env.SESSION_SECRET === 'your_session_secret_here_change_in_production_min_32') {
      warnings.push('Default SESSION_SECRET detected in production');
    }
  }

  if (missing.length > 0) {
    return {
      name: 'Environment Variables',
      status: 'fail',
      message: `Missing required: ${missing.join(', ')}`,
      canRepair: false,
      repairHint: `Set the required environment variables in .env file or environment`,
      details: { missing, present, invalid }
    };
  }

  if (invalid.length > 0) {
    return {
      name: 'Environment Variables',
      status: 'fail',
      message: `Invalid values: ${invalid.map(i => i.key).join(', ')}`,
      canRepair: false,
      repairHint: `Fix the invalid environment variable values`,
      details: { present, invalid }
    };
  }

  if (warnings.length > 0) {
    return {
      name: 'Environment Variables',
      status: 'warn',
      message: `All required present, but ${warnings.length} warning(s)`,
      canRepair: false,
      repairHint: warnings.join('; '),
      details: { present, warnings }
    };
  }

  return {
    name: 'Environment Variables',
    status: 'pass',
    message: `${present.length} environment variables configured`,
    details: { present }
  };
}

/**
 * Repair environment - create .env file template
 * @returns {Promise<void>}
 */
export async function repairEnvironment() {
  const fs = await import('fs/promises');
  const { join } = await import('path');

  const envPath = join(process.cwd(), '.env');

  try {
    await fs.access(envPath);
    throw new Error('.env file already exists');
  } catch (err) {
    if (err.code !== 'ENOENT') throw err;
  }

  const template = `# CogniMesh Environment Configuration
# Generated by doctor --repair

# Required
GITHUB_TOKEN=your_github_token_here
JWT_SECRET=your_secure_random_secret_min_32_chars

# Optional with defaults
DATABASE_PATH=./data/cognimesh.db
STATE_PATH=./data/state
COGNIMESH_PORT=3000
NODE_ENV=development
`;

  await fs.writeFile(envPath, template, 'utf-8');
}

export default checkEnvironment;
